# docker.io/elasticsearch
"registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_library_elasticsearch:/^(.*)(-n-ext)$/":
  private: docker-hosted.nstl-dev.com/library/elasticsearch
# docker.io/jetbrains/teamcity-agent
"registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_jetbrains_teamcity-agent:/^(.*)(-n-ext)$/":
  private: docker-hosted.nstl-dev.com/jetbrains/teamcity-agent
# docker.io/adoptopenjdk/openjdk11
"registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_adoptopenjdk_openjdk11:/^(.*)(-n-ext)$/":
  private: docker-hosted.nstl-dev.com/adoptopenjdk/openjdk11
# docker.io/sphinxdoc/sphinx-latexpdf
"registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_sphinxdoc_sphinx-latexpdf:/^(.*)(-n-ext)$/":
  private: docker-hosted.nstl-dev.com/sphinxdoc/sphinx-latexpdf