########################################################################################### docker-hosted.nstl-dev.com/caas
# docker-hosted.nstl-dev.com/caas/nlp-brat
# Tag list: http://docker-hosted.nstl-dev.com/harbor/projects/68/repositories/nlp-brat/artifacts-tab
"docker-hosted.nstl-dev.com/caas/nlp-brat:1.3.0": "registry.cn-beijing.aliyuncs.com/ninemax/caas_nlp-brat"

# docker-hosted.nstl-dev.com/caas/kgms
# Tag list: http://docker-hosted.nstl-dev.com/harbor/projects/68/repositories/kgms/artifacts-tab
"docker-hosted.nstl-dev.com/caas/kgms:latest": "registry.cn-beijing.aliyuncs.com/ninemax/caas_kgms"